'use client';
import {useEffect,useState} from 'react';import {FORMS} from '../../lib/forms';
const post=b=>fetch('/api/admin',{method:'POST',body:JSON.stringify(b)});
const Ic=({d})=><svg width="26" height="26" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d={d}/></svg>;
const STAGES=['application','interview','offer','pre-employment checks','started'];
const ini=n=>(n||'?').split(' ').map(x=>x[0]).join('').slice(0,2).toUpperCase();
const ago=t=>{const m=(Date.now()-new Date(t))/6e4;return m<60?'just now':m<1440?'today':Math.floor(m/1440)+'d ago'};
export default function A(){
const [rows,setRows]=useState(null);const [em,setEm]=useState('');const [pw,setPw]=useState('');const [msg,setMsg]=useState('');
const [q,setQ]=useState('');const [st,setSt]=useState('');const [sel,setSel]=useState([]);const [open,setOpen]=useState(null);const [nw,setNw]=useState(false);
const [nf,setNf]=useState({name:'',email:'',position:'',home:''});const [rf,setRf]=useState('application');const [rn,setRn]=useState('');const [stg,setStg]=useState(STAGES[1]);
const load=async()=>{const r=await post({a:'list'});setRows(r.ok?await r.json():false)};useEffect(()=>{load()},[]);
const act=async(b,t,after)=>{const r=await post(b);setMsg(r.ok?t:'Something went wrong. Please try again.');if(r.ok&&after)after();load()};
if(rows===null)return <p style={{padding:30}}>Loading...</p>;
if(rows===false)return <div className="lg"><div className="lp"><img src="/logo.jpg" alt="Harbour Light Home for Children"/><div><h2>Welcoming new colleagues to our children&apos;s home, safely.</h2><ul style={{padding:0}}><li style={{'--c':'#1d2f5c'}}>Step-by-step candidate onboarding</li><li style={{'--c':'#5b7fc0'}}>Safer recruitment progress tracking</li><li style={{'--c':'#1f8a4c'}}>Reference requests and staff files</li></ul></div><small>Harbour Light Home Ltd &middot; Residential care for children</small></div>
<div className="rp"><form onSubmit={async x=>{x.preventDefault();const r=await post({a:'login',email:em,password:pw});if(r.ok)load();else setMsg('Email or password is incorrect.')}}><h1>Sign in</h1><p>Access is limited to Harbour Light staff.</p><label>Email</label><input type="email" value={em} onChange={x=>setEm(x.target.value)} autoComplete="username"/><label>Password</label><input type="password" value={pw} onChange={x=>setPw(x.target.value)} autoComplete="current-password"/><button type="submit" style={{marginTop:22}}>Sign in</button><p role="status" style={{color:'#b3382c'}}>{msg}</p></form></div></div>;
const cnt=s=>rows.filter(c=>c.status===s).length;
const list=rows.filter(c=>(c.name+c.email).toLowerCase().includes(q.toLowerCase())&&(!st||c.status===st));
const tg=id=>setSel(sel.includes(id)?sel.filter(x=>x!==id):[...sel,id]);
const csv=()=>{const l=[['Name','Email','Position','Home','Forms','References back','Status','Stage'],...rows.map(c=>[c.name,c.email,c.position,c.home,c.n+'/'+c.total,c.back+'/'+c.refs.length,c.status,c.stage])].map(r=>r.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([l],{type:'text/csv'}));a.download='candidates.csv';a.click()};
const o=rows.find(x=>x.id===open);
return <div><header className="top"><div className="brand"><img src="/logo.jpg" alt="Harbour Light Home for Children"/><div><b>Harbour Light</b><br/><small>Onboarding &mdash; Staff</small></div></div><span className="pill">Candidates</span><span className="pill"><span className="av">HR</span>Hr<button className="alt" style={{margin:0,padding:'4px 12px'}} onClick={()=>act({a:'logout'},'',()=>setRows(false))}>Sign out</button></span></header>
<main className="wrap"><div className="hero"><div><h1>Candidates</h1><span>Safer recruitment onboarding across all homes</span></div><div><button className="alt" onClick={csv}>Export CSV</button><button onClick={()=>setNw(true)}>+ New candidate</button></div></div>
<p role="status" style={{minHeight:22,margin:'8px 4px'}}>{msg}</p>
<div className="stats"><div className="stat"><span className="t"><Ic d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8M23 21v-2a4 4 0 0 0-3-3.9M16 3.1a4 4 0 0 1 0 7.8"/></span><div><b>{cnt('In progress')}</b><small>In progress</small></div></div><div className="stat"><span className="t"><Ic d="M12 22a10 10 0 1 0 0-20 10 10 0 0 0 0 20M12 6v6l4 2"/></span><div><b>{cnt('References')}</b><small>Awaiting review</small></div></div><div className="stat"><span className="t"><Ic d="M22 11.1V12a10 10 0 1 1-5.9-9.1M22 4 12 14l-3-3"/></span><div><b>{cnt('Complete')}</b><small>Complete</small></div></div></div>
<div className="tools"><input placeholder="Search name or email" value={q} onChange={x=>setQ(x.target.value)}/><select value={st} onChange={x=>setSt(x.target.value)} aria-label="Status"><option value="">All statuses</option><option>In progress</option><option>References</option><option>Complete</option></select></div>
<div className="bulk"><b>{sel.length} selected</b><button className="alt" disabled={!sel.length} onClick={()=>act({a:'resend',ids:sel},'Invites resent')}>Resend invite</button><select value={stg} onChange={x=>setStg(x.target.value)} aria-label="Stage">{STAGES.map(s=><option key={s}>{s}</option>)}</select><button className="alt" disabled={!sel.length} onClick={()=>act({a:'stage',ids:sel,stage:stg},'Stage updated')}>Set stage</button></div>
<div className="tw"><table><thead><tr><th/><th>Candidate</th><th>Position / Home</th><th>Progress</th><th>Refs</th><th>Status</th><th>Last activity</th></tr></thead><tbody>
{list.map(c=><tr className="row" key={c.id} onClick={()=>setOpen(c.id)}><td onClick={e=>e.stopPropagation()}><input type="checkbox" aria-label={'Select '+c.name} checked={sel.includes(c.id)} onChange={()=>tg(c.id)}/></td><td><div className="who"><span className="av">{ini(c.name)}</span><div><b>{c.name}</b><small>{c.email}</small></div></div></td><td>{c.position||'-'}<small>{c.home}{c.stage?' · '+c.stage:''}</small></td><td>{c.n}/{c.total}</td><td>{c.refs.length?c.back+'/'+c.refs.length+' back':'-'}</td><td><span className={'st '+c.status}>{c.status}</span></td><td>{ago(c.last)}</td></tr>)}
{!list.length&&<tr><td colSpan="7" style={{textAlign:'center',padding:30}}>No candidates yet. Choose New candidate to send the first invite.</td></tr>}</tbody></table></div></main>
{nw&&<div className="ov"><div className="md"><h2>New candidate</h2>{[['name','Full name'],['email','Email'],['position','Position'],['home','Home']].map(([k,l])=><div key={k}><label>{l}</label><input value={nf[k]} onChange={x=>setNf({...nf,[k]:x.target.value})}/></div>)}<button disabled={!nf.name||!nf.email} onClick={()=>act({a:'invite',...nf},'Invite sent',()=>{setNw(false);setNf({name:'',email:'',position:'',home:''})})}>Send invite link</button><button className="alt" onClick={()=>setNw(false)}>Cancel</button></div></div>}
{o&&<div className="ov" onClick={()=>setOpen(null)}><div className="md" onClick={e=>e.stopPropagation()}><h2>{o.name}</h2><p>{o.email}<br/>{o.position} {o.home}</p><b>{o.pct}% complete</b><div className="bar"><i style={{width:o.pct+'%'}}/></div>
<p>{FORMS.map(f=>{const s=o.forms[f.key];return <span key={f.key} className={'chip '+(s==='submitted'?'ok':s==='returned'?'ret':s?'dr':'')}>{f.title}</span>})}</p>
<p><b>References:</b> {o.refs.length?o.refs.map(r=><span key={r.n} className={'chip '+(r.status==='received'?'ok':'')}>{r.name}: {r.status==='received'?'received':'sent'}{r.status!=='received'&&<a href="#" onClick={ev=>{ev.preventDefault();act({a:'markref',id:o.id,n:r.n},'Marked received')}}> mark received</a>}</span>):'none sent yet'}</p>
<button disabled={o.forms.references!=='submitted'} onClick={()=>act({a:'sendref',id:o.id},'Reference requests sent')}>Send references</button>
<label>Return a form to the candidate</label><select value={rf} onChange={x=>setRf(x.target.value)}>{FORMS.map(f=><option key={f.key} value={f.key}>{f.title}</option>)}</select><textarea placeholder="What should they fix?" value={rn} onChange={x=>setRn(x.target.value)}/>
<button className="alt" disabled={!rn} onClick={()=>act({a:'return',id:o.id,form:rf,note:rn},'Returned to candidate',()=>setRn(''))}>Return form</button><button className="alt" onClick={()=>setOpen(null)}>Close</button></div></div>}</div>}
