const L=(k,l,t,o,s)=>({k,l,t:t||'text',o,s});
const refs=[1,2,3].flatMap(n=>[L(`r${n}n`,`Referee ${n}: name`,'text',n>2),L(`r${n}c`,`Referee ${n}: company`,'text',n>2),L(`r${n}p`,`Referee ${n}: contact number`,'text',n>2),L(`r${n}e`,`Referee ${n}: email`,'email',n>2)]);
export const FORMS=[
{key:'application',title:'Application Form',f:[L('post','Post applied for'),L('first','First name'),L('last','Last name'),L('address','Address','area'),L('phone','Telephone'),L('email','Email','email'),L('licence','Current driving licence?','yn'),L('car','Use of a car for work?','yn'),L('rtw','Right to work in the UK?','yn'),L('share','Share code (9 characters)','text',1),L('edu','Education and qualifications from age 11 (dates, school, grades)','area'),L('train','Training and professional bodies','area',1),L('emp','Employment history, most recent first (employer, dates, duties, reason for leaving, salary)','area'),L('vol','Voluntary work and other experience','area',1),L('why','Why are you applying?','area'),L('support','Information in support of your application','area'),L('essay','Written exercise: which attitudes and skills matter in a children\'s residential care setting, and what are children\'s essential needs?','area'),L('start','Earliest start date','date'),L('disc','Disciplinary action received (if any)','area',1)]},
{key:'gaps',title:'Employment History: Gaps',f:[L('gaps','Explain any gaps in your employment (dates and what you were doing). Write "None" if there are none.','area')]},
{key:'dbs',title:'DBS and Declaration',f:[L('valid','Do you have a valid DBS?','yn'),L('num','DBS number','text',1),L('upd','Registered with the DBS Update Service?','yn'),L('updn','Update Service number','text',1),L('conv','Have you ever been convicted, cautioned, bound over, or have a conviction pending?','yn'),L('d1','Date and nature of the offence (include your age and the victim\'s age where relevant)','area',0,['conv','Yes']),L('d2','Date, court and sentence for each offence','area',0,['conv','Yes']),L('d3','Isolated incident or pattern?','area',0,['conv','Yes']),L('d4','Context at the time','area',0,['conv','Yes']),L('d5','Lessons learnt','area',0,['conv','Yes'])]},
{key:'starter',title:'New Starter Details',f:[L('sn','Surname'),L('fn','First name(s)'),L('dob','Date of birth','date'),L('addr','Address and postcode','area'),L('tel','Contact number'),L('ni','National Insurance number'),L('bank','Bank name'),L('sort','Sort code'),L('acc','Account number'),L('accn','Account name'),L('nk','Next of kin: name'),L('nkr','Next of kin: relationship'),L('nkt','Next of kin: telephone'),L('hmrc','HMRC starter statement','select:A: first job since 6 April,B: only job now but had another since 6 April,C: I have another job or a pension'),L('sl','Student loan','select:None,Type 1,Type 2'),L('p45','Do you have a P45 from your previous employer?','yn'),L('nest','NEST workplace pension (3% employer, 5% you)','select:I want to join,I do not want to join')]},
{key:'health',title:'Health Questionnaire',f:[L('abs','Days of absence from work in the last 3 years'),L('med','Currently on medication (excluding contraceptives)? Give details','area'),L('hosp','Hospital stays in the last 3 years? Give details','area'),L('cond','Any injury, illness, condition or allergy that might affect your duties? Give details','area'),L('joint','Any problems with back, neck, arms, legs or joints? Give details','area'),L('dis','Do you consider yourself to have a disability? Give details','area')]},
{key:'references',title:'References',f:[L('auth','I authorise Harbour Light HR to contact my referees and verify references','check'),...refs]},
{key:'confidentiality',title:'Confidentiality Agreement',f:[L('agree','I have read and agree to the Employee Confidentiality Agreement with Harbour Light Home Ltd','check')]}];
