export const dynamic='force-dynamic';
import {cookies} from 'next/headers';import {db,tok,adm,mail} from '../../../lib/db';import {FORMS,calc} from '../../../lib/forms';
const S=process.env.SITE_URL;const J=(o,s)=>Response.json(o,{status:s||200});
const invite=(c)=>mail(c.email,'Your Harbour Light onboarding',`<p>Dear ${c.name},</p><p>Please complete your onboarding using this secure link:</p><p><a href="${S}/c/${c.token}">${S}/c/${c.token}</a></p><p>You can save and return at any time.</p><p>Kind regards,<br>HR, Harbour Light Home for Children</p>`);
export async function POST(req){try{return await h(req)}catch(e){return J({error:'Server error: '+e.message},500)}}
async function h(req){const b=await req.json();
if(b.a==='login'){if(String(b.email).trim().toLowerCase()!==String(process.env.ADMIN_EMAIL).trim().toLowerCase()||b.password!==process.env.ADMIN_PASSWORD)return J({},401);cookies().set('adm',adm(),{httpOnly:true,secure:true,sameSite:'strict',path:'/'});return J({ok:1})}
if(b.a==='logout'){cookies().delete('adm');return J({ok:1})}
if(cookies().get('adm')?.value!==adm())return J({},401);
if(b.a==='list'){const {data:c}=await db.from('candidates').select('*').order('created_at',{ascending:false});const {data:r}=await db.from('responses').select('candidate_id,form_key,status,updated_at,data');const {data:f}=await db.from('referees').select('candidate_id,n,name,status');
return J((c||[]).map(x=>{const rs=(r||[]).filter(y=>y.candidate_id===x.id);const n=rs.filter(y=>y.status==='submitted').length;const refs=(f||[]).filter(y=>y.candidate_id===x.id);const back=refs.filter(y=>y.status==='received').length;
const status=n<FORMS.length?'In progress':(refs.length&&back===refs.length?'Complete':'References');
const last=[x.created_at,...rs.map(y=>y.updated_at)].sort().pop();
return {...x,forms:Object.fromEntries(rs.map(y=>[y.form_key,y.status])),n,total:FORMS.length,pct:calc(Object.fromEntries(rs.map(y=>[y.form_key,y]))),refs,back,status,last}}))}
if(b.a==='invite'){const t=tok();const c={name:b.name,email:b.email,position:b.position,home:b.home,token:t};const {error}=await db.from('candidates').insert(c);if(error)return J({error:'Could not save the candidate: '+error.message},400);const m=await invite(c);if(!m.ok)return J({error:'Candidate saved, but the email failed ('+m.status+'). Check GMAIL_USER and GMAIL_APP_PASSWORD in the hosting settings, then use Resend invite.'},502);return J({ok:1})}
if(b.a==='resend'){const {data:cs}=await db.from('candidates').select('*').in('id',b.ids);for(const c of cs||[])await invite(c);return J({ok:1})}
if(b.a==='stage'){await db.from('candidates').update({stage:b.stage}).in('id',b.ids);return J({ok:1})}
if(b.a==='return'){await db.from('responses').update({status:'returned',note:b.note}).eq('candidate_id',b.id).eq('form_key',b.form);const {data:c}=await db.from('candidates').select('*').eq('id',b.id).single();await mail(c.email,'Please update your onboarding form',`<p>Dear ${c.name},</p><p>Please update the form "${FORMS.find(f=>f.key===b.form).title}": ${b.note}</p><p><a href="${S}/c/${c.token}">Open your onboarding</a></p>`);return J({ok:1})}
if(b.a==='sendref'){const {data:c}=await db.from('candidates').select('*').eq('id',b.id).single();const {data:r}=await db.from('responses').select('data').eq('candidate_id',b.id).eq('form_key','references').maybeSingle();if(!r)return J({},400);
for(const n of [1,2,3]){const d=r.data,e=d[`r${n}e`];if(!e)continue;const {data:x}=await db.from('referees').select('status').eq('candidate_id',b.id).eq('n',n).maybeSingle();if(x&&x.status==='received')continue;const t=tok();await db.from('referees').upsert({candidate_id:b.id,n,name:d[`r${n}n`],email:e,token:t,status:'sent'});
await mail(e,`Reference request for ${c.name} - Harbour Light Home for Children`,`<p>Dear ${d[`r${n}n`]},</p><p>${c.name} has applied to Harbour Light Home for Children and named you as a referee, authorising us to contact you as part of our safer recruitment checks.</p><p>Please complete the short reference form here (about 5 minutes):</p><p><a href="${S}/r/${t}">${S}/r/${t}</a></p><p>Your response is confidential. Questions? Reply to this email.</p><p>Kind regards,<br>HR / Compliance Team<br>Harbour Light Home for Children</p>`)}return J({ok:1})}
if(b.a==='files'){const {data:r}=await db.from('responses').select('form_key,data').eq('candidate_id',b.id);const it=[];for(const x of r||[]){const F=FORMS.find(y=>y.key===x.form_key);if(!F)continue;for(const f of F.f)if(f.t==='file')for(const m of (x.data&&x.data[f.k])||[])it.push({form:F.title,label:f.l,name:m.name,path:m.path})}
const {data:u}=it.length?await db.storage.from('candidate-files').createSignedUrls(it.map(i=>i.path),3600):{data:[]};return J(it.map((i,k)=>({form:i.form,label:i.label,name:i.name,url:u&&u[k]&&u[k].signedUrl})))}
if(b.a==='update'){const {error}=await db.from('candidates').update({name:b.name,email:b.email,position:b.position,home:b.home}).eq('id',b.id);if(error)return J({error:'Could not save: '+error.message},400);return J({ok:1})}
if(b.a==='delete'){if(!Array.isArray(b.ids)||!b.ids.length)return J({error:'Nothing selected'},400);{const {data:rr}=await db.from('responses').select('data,form_key').in('candidate_id',b.ids);const ps=[];for(const x of rr||[]){const F=FORMS.find(y=>y.key===x.form_key);if(F)for(const f of F.f)if(f.t==='file')for(const m of (x.data&&x.data[f.k])||[])ps.push(m.path)}if(ps.length)await db.storage.from('candidate-files').remove(ps)}await db.from('responses').delete().in('candidate_id',b.ids);await db.from('referees').delete().in('candidate_id',b.ids);const {data:gone,error}=await db.from('candidates').delete().in('id',b.ids).select('id');if(error)return J({error:'Could not delete: '+error.message},400);if(!gone||!gone.length){const {data:left}=await db.from('candidates').select('id').in('id',b.ids);if(left&&left.length)return J({error:'The database refused to delete. Check that SUPABASE_SERVICE_KEY in the hosting settings is the service_role key, not the anon or publishable key.'},403);return J({ok:1,deleted:0})}return J({ok:1,deleted:gone.length})}
if(b.a==='markref'){await db.from('referees').update({status:'received'}).eq('candidate_id',b.id).eq('n',b.n);return J({ok:1})}
return J({},400)}
